### ISSUE TITLE
Error when used with SSR

### ISSUE THREAD

**Issue by j-jackson** [jamesmcallister/tachyons-for-styled-components#6]
Thanks for the package, its exactly what I have been looking for!

There appears to be an issue when rendering on the server:

`TypeError: Cannot read property 'raw' of undefined`

Any thoughts on what might by causing this?

![screen shot 2017-04-15 at 2 29 39 pm](https://cloud.githubusercontent.com/assets/22781082/25060770/99c60444-21e8-11e7-8c85-7f66fabf3413.png)

**Comment by jamesmcallister** [comment]
Not sure what could be causing this.

I wonder if by putting `tachyons-for-styled-components`is its own chunk, might help with debugging [webpack](https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code)
