### ISSUE TITLE
unable to resolve module ../index.js directory doesnt exist

### ISSUE THREAD

**Issue by dnecklesportfolio** [jamesmcallister/tachyons-for-styled-components#7]
A couple things 
Do i have to put the full path to the node modules path where the folder is, because its not picking it up.
also, shouldnt the file name be changed to main?

**Comment by jamesmcallister** [comment]
Sorry the readme file was wrong, you need to install via npm and use  ``import tachyons from 'styled-components-tachyons'``

I have updated the readme.

**Comment by dnecklesportfolio** [comment]
Thank you!
